### ISSUE TITLE
Consider adding support for a more mature and fleshed out architecture?

### ISSUE THREAD

**Issue by gek169** [joe7575/vm16#2]
I saw your little project and couldn't help but thinking we were writing nearly the same thing.
I'm working on a virtual portable computer architecture called "Sisa16" which intersects directly with many of your project's goals.
https://github.com/gek169/Simple_ISA
# Why should you use SISA16 over VM16?
* Tested on dozens of compilers and architectures
* Included documentation, assembler, disassembler, and minimal complete examples.
* macro-enabled assembler (With a compiler for the architecture in-development)
* Unique self-sandboxing ability- Sisa16 code can run itself.
* Works integrated or standalone. 
* Ready for deployment on unix-based systems immediately. You can write programs for this thing right now.
* Extensible. Adding new instructions is fairly easy to do (Add a new goto label followed by your code and a 'D' for dispatch, then add your instruction to the dispatch tables and the assembler's list of instructions).
* Variable length RISC instruction set that is trivial to parse.
* Endian independent
* Optional floating point unit and signed integer operations for supported platforms
* Compiletime and runtime tests implemented for environment conformance.

```c
#include "d.h"
#include "isa.h"
/*in your program...*/
/*when you want to invoke the emulator...*/
/*set up the segment and error register.*/
SEGMENT = malloc(256); SEGMENT_PAGES = 1; R=0;
/*Emulate.*/
e();
/*React to error register R.*/
if(R > 0) {puts("SISA16 ERROR");}
```
# SISA16 history/overview
I've been working on a project called "Sisa16" and I have donated my code to the public domain. The ultimate goal of the project is to produce a fast and efficient alternative to extension languages like Lua and Webassembly.

It has many more instructions, 32 bit support, and 16 megs of memory plus a "segment" which can be infinite in size. It can also sandbox its own execution (Either sharing the segment or not) which has interesting properties. The most notable limitation is that it has a segmented memory model- the 16 megs are split into 256*64k, the "far memory model". This is done for speed.

https://github.com/gek169/Simple_ISA

I have an example runtime and assembler (the assembler even lets you do macros and scripting, nifty, huh?) 

the assembler also functions as a disassembler with annotated output.

I figure you could take my code and fix it up into a Lua library for minetest? I'd love to hear about it. 

All you have to do is implement a device driver in d.h, load a memory image into the array M,  setup the segment, and call e(). You can see what you need to include in your program in the emulator, isa.c

Memory images can be created by compiling .asm files into binaries. If you have Tiny C Compiler, there's no need to compile anything, 
```
#in the cloned repo
./a.c -i clock.asm -o clockbin
./e.c clock.bin
```

# Repository structure (in case you're confused)

a.c, b.c, af.c, bf.c, e.c, and ef.c are all Tiny C Compiler scripts which I use for rapid testing. I do my development builds with GCC. Ignore them.

isa.c is the standalone runtime which compiles down to about 40k.
assembler.c is the macro-enabled assembler and disassembler with a built-in emulator. 
isa.h is the "core" of the emulator. No, we do NOT use `while(){switch(getopcode){}}` I have a dispatch (one for GNU compatible compilers that implement computed goto labels, another for ones that don't).

isa_pre.h contains the variable declarations needed for both the driver and the emulator.
d.h contains the driver.

**Comment by joe7575** [comment]
SISA16 and VM16 have completely different goals. VM16 is a KISS VM to be used inside the game Minetest to play with the assembler language.
