### ISSUE TITLE
user management?

### ISSUE THREAD

**Issue by hacknorris-code** [joe7575/vm16#3]
i know its dumb to put it in such addon but just thought about restricting access to these desktops and making perms to executing some programs in it... (aka - chmod, adduser, rmuser, usermod cmd in linux, yk)
PS: i was gonna make something similar but left it as saw this repo...

**Comment by joe7575** [comment]
This is only the VM to be used in other mods. The demo CPU is only for demonstration purposes and should be as easy as possible. It is up to you to implement a mod with such features be means of vm16 or without.

**Comment by hacknorris-code** [comment]
ok...
