### ISSUE TITLE
External real world communication (ex. http requests)

### ISSUE THREAD

**Issue by MrFasolo97** [joe7575/vm16#5]
Hi, I just wish to say that I did see this mod a few hours ago for the first time and I'm already falling in love with it and beduino mod too.
I was wondering if there is a possibility to communicate with the external real world, via HTTP requests or TCP connections.
I guess it's a little outside the mod scope right now, if there isn't such a possibility do you have any suggestion on how to make a mod to implement those new functions as an addon for your mods?
Would be wonderful to be able to pull data from the real world, imagine how many things you could do.
I would probably make a wallet for https://krist.dev/ currency right away. Pull some generic stats and display them in-game. 
And maybe make some RESTful clients. I made a software repository client for a similar mod and the server for a real computer to host that repository.
Please, let me know if it is possible with this mod itself, or how to make an addon to enable in-game computers to communicate with the real world. Obviously, it would need a whitelist for a few web services safe to connect. (Pastebin and a few others maybe?)

**Comment by joe7575** [comment]
This is a great idea and can easily be implemented as a mod.
VM16 is a sandboxed VM with no interface to the outside world. This was done on purpose. VM16 is designed to be absolutely secure.
But [Beduino](https://github.com/joe7575/beduino) is a mod with communication possibilities between Beduino controllers.
An example is the [broker](https://github.com/joe7575/beduino/blob/main/com/broker.lua).
Specific commands for Beduino controllers to communicate with the outside world can be easily added [see here](https://github.com/joe7575/beduino/blob/main/com/router.lua#L239)
