### ISSUE TITLE
logs in chat

### ISSUE THREAD

**Issue by kizeren** [joe7575/vm16#6]
Not sure what I've done.  Updated a few mods and now vm16 is showing in chat "on_load", "vm_restore", "vm_destroy" and a few others.
Anyway to turn this off?

**Comment by joe7575** [comment]
Unfortunately, you can't turn it off. This is part of the code. 
You can remove the `print` code lines like this: https://github.com/joe7575/vm16/blob/master/api.lua#L108

**Comment by kizeren** [comment]
Ok.  Thats what I was thinking but figured I would make sure just to be safe.

**Comment by kizeren** [comment]
Yep fixed it.

**Comment by kizeren** [comment]
That fixed it.

**Comment by joe7575** [comment]
Is fixed with commit [e0b288a](https://github.com/joe7575/vm16/commit/e0b288a5d6ec9c8462673ab193e4818e9459b791)
